In [1]:
import numpy as np

## Creating Arrays with Zeros, Ones, or Constants

In [2]:
zeros_array = np.zeros(10)
zeros_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
ones_array = np.ones(10)
ones_array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
constant_array = np.full(10, 3)
constant_array

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [5]:
arr = np.array([1,2,3,4,5,6,7,8,9,0])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [6]:
arr[9] = 10

In [7]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [9]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## Multi-dementional array

In [10]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [28]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])

In [29]:
n[2]

array([7, 8, 9])

In [30]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
n[:, 2]

array([3, 6, 9])

In [32]:
n[:, 2] = [1, 1, 1]
n

array([[1, 2, 1],
       [4, 5, 1],
       [7, 8, 1]])

## Randomly generated arrays

In [43]:
np.random.seed(2)
100 * np.random.rand(5, 2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [38]:
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [45]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

## Element-wise operation

In [47]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [49]:
arr + 2

array([2, 3, 4, 5, 6])